[platformio]   
;    default_envs = nano
    default_envs = esp32-c3
    
;   src_dir = src
;    src_dir = examples/receive
;    src_dir = examples/config
;    src_dir = examples/webDisplay


 [env]
     lib_deps = 


[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 57600    
monitor_speed = 9600   
lib_deps = sui77/rc-switch
build_src_filter = +<main_Arduino.cpp>
;upload_port = COM4


[env:esp32-c3]
platform = espressif32@6.5.0
board = lolin_c3_mini
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=0
    -DCORE_DEBUG_LEVEL=3
    -DARDUINOJSON_POSITIVE_EXPONENTIATION_THRESHOLD=1e9
    -DPIN_SYSMODE=GPIO_NUM_1
    -DPIN_RECEIVER_PWR=GPIO_NUM_2
    -DPIN_LED=GPIO_NUM_8    
    -DPIN_SDA=GPIO_NUM_6   
    -DPIN_SCL=GPIO_NUM_7

lib_deps =
    ${env.lib_deps}
    https://github.com/DanielKnoop/ESPAsyncWebServer#1.2.7
    https://github.com/Oxi75/homee-api-esp32
    https://github.com/bblanchon/arduinojson#v6.17.3
build_src_filter = +<*> -<main_Arduino.cpp>

monitor_filters = 
    esp32_exception_decoder
    time