[platformio]   
;    default_envs = nano
    default_envs = esp32dev

;   src_dir = src
;    src_dir = examples/receive
;    src_dir = examples/webDisplay


 [env]
     lib_deps = 


[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 57600    
monitor_speed = 9600   
lib_deps = sui77/rc-switch
build_src_filter = +<main_Arduino.cpp>
;upload_port = COM4

[env:esp32dev]
    platform = espressif32@6.5.0
    board = esp32dev
    framework = arduino
    upload_speed = 921600
    monitor_speed = 115200
    board_build.filesystem = littlefs
    build_flags = 
        -DARDUINOJSON_POSITIVE_EXPONENTIATION_THRESHOLD=1e9    
            
    build_src_filter = +<*> -<main_Arduino.cpp>

    lib_deps =
        ${env.lib_deps}
        https://github.com/DanielKnoop/ESPAsyncWebServer#1.2.7
        https://github.com/Oxi75/homee-api-esp32
        https://github.com/bblanchon/arduinojson#v6.17.3



[env:esp12e]
    platform = espressif8266
    board = esp12e
    framework = arduino
    lib_deps = 
        ESP8266WiFi
;       ESPAsyncTCP
;        ESPAsyncWebServer
        ArduinoOTA
        DNSServer
        https://github.com/me-no-dev/ESPAsyncTCP
        https://github.com/DanielKnoop/ESPAsyncWebServer
        https://github.com/DanielKnoop/ESPAsyncUDP
        https://github.com/Oxi75/homee-api-esp32        
    upload_speed = 115200
    monitor_speed = 74880 
    board_build.filesystem = littlefs
    build_flags = 
        -DARDUINOJSON_POSITIVE_EXPONENTIATION_THRESHOLD=1e9    
